name: attendance_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.17.0
  http: ^1.2.2
  image_picker: ^0.8.7
  sqflite: ^2.2.5
  path: ^1.8.3
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff" # White background color for the splash screen
  image: assets/splash_icon.png # Path to your splash image
  android: true
  ios: true
  web: false
